In [2]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

## We need to pass this data , but first we need to transform and scale data. SO now
##lets load the gender encoders and geography one hot encoding

In [3]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd

WARNING:tensorflow:From c:\avishek_work\Machine Learning Projects\ANN Project\.conda\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [4]:
my_model = load_model('model.h5')

## Reading the label encoder and one hot encoder as well as scaler


with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('one_hot_encoder_geo.pkl','rb') as file:
    one_hot_encoder_geo=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:tensorflow:From c:\avishek_work\Machine Learning Projects\ANN Project\.conda\lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [5]:
# Transform the input data to Dataframe

data=pd.DataFrame([input_data])

In [6]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [7]:
data['Gender']=label_encoder_gender.transform(data['Gender'])

In [8]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [9]:
array_geography=one_hot_encoder_geo.transform(data[['Geography']]).toarray()

geo_encoded_df=pd.DataFrame(array_geography,columns=one_hot_encoder_geo.get_feature_names_out())

In [10]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [11]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [12]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [13]:
input_scaled=scaler.transform(data)
input_scaled

array([[-0.47154541,  0.90911166,  0.09477172, -0.69844549, -0.29010416,
         0.80510537,  0.63367318,  0.95214374, -0.84805047,  0.98019606,
        -0.57581067, -0.56349184]])

In [14]:
prediction=my_model.predict(input_scaled)

1/1 [==============================] - 1s 690ms/step

In [15]:
prediction

array([[0.05154872]], dtype=float32)

In [16]:
prediction_probability=prediction[0][0]

In [17]:
if prediction_probability>0.5:
    print("Will churn")
else:
    print("Won't Churn")

Won't Churn

In [23]:
one_hot_encoder_geo.categories_[0]

array(['France', 'Germany', 'Spain'], dtype=object)

In [25]:
label_encoder_gender.classes_

array(['Female', 'Male'], dtype=object)